### ISSUE TITLE
java.lang.ArithmeticException: Division by zero

### ISSUE THREAD

**Issue by kishortradelab** [TahaMalas/internet_speed_test#33]
Fatal Exception: java.lang.ArithmeticException: Division by zero
       at java.math.BigDecimal.divide(BigDecimal.java:1030)
       at fr.bmartel.speedtest.RepeatWrapper.getRepeatReport(RepeatWrapper.java:123)
       at fr.bmartel.speedtest.SpeedTestTask.getReport(SpeedTestTask.java:211)
       at fr.bmartel.speedtest.SpeedTestSocket.getLiveReport(SpeedTestSocket.java:10)
       at fr.bmartel.speedtest.RepeatWrapper$2.run(RepeatWrapper.java:41)
       at java.util.TimerThread.mainLoop(TimerThread.java:562)
       at java.util.TimerThread.run(TimerThread.java:512)

- Reported crash issue in Android devices only

**Comment by D-Mick** [comment]
Experiencing the same thing, any solution?

**Comment by shaz-tech** [comment]
@kishortradelab @D-Mick  Checkout https://pub.dev/packages/flutter_internet_speed_test
